### ISSUE TITLE
Makefile for Doc/ ?

### ISSUE THREAD

**Issue by guicho271828** [gpwwjr/GECO#1]

**Comment by gpwwjr** [comment]
I don't have one.

Producing documents with TeX requires a good bit of infrastructure that many developers don't have. I use an interactive gui-based tool called TeXstudio, which is part of the TeX LIve distribution (http://www.tug.org/texlive/).

If you're familiar with using TeX to produce documents, it's relatively straightforward to produce the GECO documentation, using either command-line tools or a gui-based approach.

**Comment by gpwwjr** [comment]
This is one reason why I include pre-built documentation with the release.

**Comment by guicho271828** [comment]
I am an academic, just need to know which file to typeset

**Comment by gpwwjr** [comment]
Docs/geco.tex

**Comment by guicho271828** [comment]
Thank you very much

**Comment by guicho271828** [comment]
I have TeX Live 2020, but it seems `code-os.sty` is missing. CTAN does not show code-os as a package.
https://www.ctan.org/search?phrase=code-os
It seems this file is your custom style file?

**Comment by gpwwjr** [comment]
I apologize. There are three style files that were missing: code-os.sty, code.sty, and verbatim.sty. The version of verbatim.sty that I used is slightly different from the one in the TeX Live 2020 distribution (and I assume it's different from CTAN as well). I'm not sure what the differences are, or even if they matter, so I've added all my local style files to a new release.

I've just published a v2.1.1a release that addresses the missing style files, and added a README.txt file to the Docs subdirectory to provide a little information about building the documentation from sources. This also includes an additional note about how to create the hyperlinked version of the documentation. And I've also updated the CHANGES.txt file.

Hopefully this will solve all of your problems.

**Comment by guicho271828** [comment]
> I apologize. 

Oh please don't. I just wanted to make the pdf buildable by anyone. It is a default nature of human to forget something.
btw I made a pull request with a makefile, please take a look at your convenience

**Comment by gpwwjr** [comment]
I completely agree about human nature.

Re the pull request- I'm a newbie with git and github, so it may take me a little while to figure out how to handle this, but I really appreciate your effort.

Thanks,

--george

**Comment by gpwwjr** [comment]
I've merged your pull request into the main branch. Thanks!
